# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 04:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import website.models
import website.profile


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email address already exists'}, help_text='Must be a @berkeley.edu email', max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=25, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last Name')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_login', models.BooleanField(default=True)),
                ('is_founder', models.BooleanField(default=False, verbose_name='Is Founder')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', website.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=40, verbose_name='Company')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Position')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('currently_working', models.BooleanField(default=False)),
                ('end_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='End Date')),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='images/default/default-logo.jpg', upload_to=website.profile.company_logo_path)),
                ('startup_name', models.CharField(max_length=99, verbose_name='Startup Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('stage', models.CharField(choices=[('0', 'Idea'), ('1', 'Prototype'), ('2', 'Incorporated'), ('3', 'Generating Revenue'), ('4', 'Seed'), ('5', 'Series A'), ('6', 'Series B'), ('7', 'Series C')], default='0', max_length=1, verbose_name='Stage')),
                ('employee_count', models.IntegerField(default=1, verbose_name='Employees')),
                ('display_funding', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('field', models.CharField(blank=True, choices=[('EDUC', 'Education'), ('TECH', 'Technology'), ('RE', 'Retail'), ('HEAL', 'Health Care'), ('ECOM', 'E-Commerce'), ('MARK', 'Marketplaces'), ('FIN', 'Finance'), ('HARD', 'Hardware'), ('MANG', 'Management/Consulting'), ('LEG', 'Legal'), ('MED', 'Medical'), ('HOUS', 'Real Estate'), ('AUTO', 'Automotive'), ('ENER', 'Energy'), ('MACH', 'Machinery'), ('ENV', 'Environmental'), ('NONE', 'Other')], max_length=4, verbose_name='Field')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('0', 'Seed'), ('1', 'Series A'), ('2', 'Series B'), ('3', 'Series C')], default='0', max_length=1, null=True, verbose_name='Stage')),
                ('raised', models.IntegerField(default=0, verbose_name='Raised')),
                ('founder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Founder')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, verbose_name='Job Title')),
                ('pay', models.CharField(choices=[('0', 'Partnership'), ('1', 'Paid')], default='1', max_length=1, verbose_name='Pay')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('level', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('IN', 'Intern')], default='FT', max_length=2, verbose_name='Level')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('founder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Founder')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Bio')),
                ('image', models.ImageField(blank=True, default='images/default/default-profile.jpg', upload_to=website.profile.user_directory_path)),
                ('position', models.CharField(blank=True, choices=[('0', 'Partnership'), ('1', 'Paid')], max_length=1, verbose_name='Position')),
                ('interests', models.TextField(blank=True, max_length=500, verbose_name='Interests')),
                ('skills', models.TextField(blank=True, max_length=500, verbose_name='Skills')),
                ('courses', models.TextField(blank=True, max_length=400, verbose_name='Courses')),
                ('alt_email', models.EmailField(max_length=255, null=True, unique=True)),
                ('year', models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate'), ('PH', 'PhD'), ('PD', 'Post-Doc'), ('AL', 'Alumni'), ('UND', 'Undecided')], max_length=2, verbose_name='Year')),
                ('hours_week', models.CharField(choices=[('0', '0 - 5'), ('1', '5 - 10'), ('2', '10 - 15'), ('3', '15 - 20'), ('4', '20+')], default='0', max_length=1, verbose_name='Hours per Week')),
                ('has_startup_exp', models.BooleanField(default=False, verbose_name='Startup Experience')),
                ('has_funding_exp', models.BooleanField(default=False, verbose_name='Funding Experience')),
                ('linkedin', models.URLField(blank=True, verbose_name='Linkedin')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('github', models.URLField(blank=True, verbose_name='Github')),
                ('major', models.CharField(choices=[('EECS', 'Electrical Engineering and Computer Science'), ('IEOR', 'Industrial Engineering and Operations Research'), ('ECON', 'Economics'), ('AMATH', 'Applied Math'), ('CHEM', 'Chemistry'), ('PHYS', 'Physics'), ('MECH', 'Mechanical Engineering'), ('BIOE', 'Bioengineering'), ('CS', 'Computer Science'), ('STAT', 'Statistics'), ('HAAS', 'Business'), ('PH', 'Public Health'), ('MCB', 'MCB'), ('BIO', 'Biology'), ('UND', 'Undecided'), ('NONE', 'Other')], default='UND', max_length=4, verbose_name='Major')),
                ('role', models.CharField(blank=True, choices=[('MARK', 'Marketing'), ('BIZ', 'Business/Administration'), ('SALE', 'Sales'), ('DES', 'Design'), ('PM', 'Product Manager'), ('CS', 'Software engineer'), ('HARD', 'Hardware engineer'), ('IOS', 'Mobile developer'), ('CONS', 'Consulting'), ('HR', 'Human resources'), ('NONE', 'Other')], max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Profile'),
        ),
    ]
