# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 23:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models
import website.profile


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email address already exists'}, help_text='Must be a @berkeley.edu email', max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_login', models.BooleanField(default=True)),
                ('is_founder', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', website.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=40)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='images/default/default-logo.jpg', upload_to=website.profile.company_logo_path)),
                ('startup_name', models.CharField(max_length=99)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('hours_wanted', models.CharField(blank=True, choices=[('0', '0 - 5'), ('1', '5 - 10'), ('2', '10 - 15'), ('3', '15 - 20'), ('4', '20+')], max_length=1)),
                ('seeking', models.CharField(blank=True, choices=[('0', 'Partnership'), ('1', 'Paid')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40)),
                ('pay', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('level', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('IN', 'Intern')], default='FT', max_length=2)),
                ('founder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Founder')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, default='images/default/default-profile.jpg', upload_to=website.profile.user_directory_path)),
                ('position', models.CharField(blank=True, choices=[('0', 'Partnership'), ('1', 'Paid')], max_length=1)),
                ('interests', models.TextField(blank=True, max_length=500)),
                ('skills', models.TextField(blank=True, max_length=500)),
                ('courses', models.TextField(blank=True, max_length=400)),
                ('year', models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2)),
                ('hours_week', models.CharField(choices=[('0', '0 - 5'), ('1', '5 - 10'), ('2', '10 - 15'), ('3', '15 - 20'), ('4', '20+')], default='0', max_length=1)),
                ('has_startup_exp', models.BooleanField(default=False)),
                ('has_funding_exp', models.BooleanField(default=False)),
                ('linkedin', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('major', models.CharField(choices=[('EECS', 'Electrical Engineering and Computer Science'), ('IEOR', 'Industrial Engineering and Operations Research'), ('ECON', 'Economics'), ('AMATH', 'Applied Math'), ('CHEM', 'Chemistry'), ('PHYS', 'Physics'), ('MECHE', 'Mechanical Engineering'), ('BIOE', 'Bioengineering'), ('CS', 'Computer Science'), ('STAT', 'Statistics'), ('HAAS', 'Business'), ('UND', 'Undecided'), ('NONE', 'Other')], default='UND', max_length=4)),
                ('role', models.CharField(blank=True, choices=[('MARK', 'Marketing'), ('BIZ', 'Business/Administration'), ('SALE', 'Sales'), ('DES', 'Design'), ('PM', 'Product Manager'), ('CS', 'Software engineer'), ('HARD', 'Hardware engineer'), ('IOS', 'Mobile developer'), ('CONS', 'Consulting'), ('HR', 'Human resources'), ('NONE', 'Other')], max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Profile'),
        ),
    ]
