# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170804_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founder',
            name='alt_email',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='pro_com',
        ),
    ]
