# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-05 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20171003_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate'), ('PH', 'PhD'), ('PD', 'Post-Doc'), ('AL', 'Alumni'), ('FC', 'Faculty'), ('NONE', 'Other')], max_length=4, verbose_name='Cal Affiliation'),
        ),
    ]
