# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170326_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.TextField(blank=True),
        ),
    ]
