# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_profile_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('MARK', 'Marketing'), ('BIZ', 'Business/Administration'), ('PM', 'Product Manager'), ('CS', 'Software engineer'), ('HARD', 'Hardware engineer'), ('IOS', 'Mobile developer'), ('CONS', 'Consulting'), ('HR', 'Human resources'), ('NONE', 'Other')], max_length=4),
        ),
    ]
