# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-10 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20171005_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hours_week',
            field=models.CharField(blank=True, choices=[('0', '1 - 5'), ('1', '5 - 10'), ('2', '10 - 15'), ('3', '15 - 20'), ('4', '20+')], max_length=1, verbose_name='Hours per Week'),
        ),
    ]
