# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170401_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='field',
            field=models.CharField(blank=True, choices=[('EDUC', 'Education'), ('TECH', 'Technology'), ('RE', 'Retail'), ('HEAL', 'Health Care'), ('ECOM', 'E-Commerce'), ('MARK', 'Marketplaces'), ('FIN', 'Finance'), ('HARD', 'Hardware'), ('MANG', 'Management/Consulting'), ('LEG', 'Legal'), ('MED', 'Medical'), ('HOUS', 'Real Estate'), ('AUTO', 'Automotive'), ('ENER', 'Energy'), ('MACH', 'Machinery'), ('ENV', 'Environmental'), ('ACC', 'Accounting'), ('NONE', 'Other')], max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(choices=[('EECS', 'Electrical Engineering and Computer Science'), ('IEOR', 'Industrial Engineering and Operations Research'), ('ECON', 'Economics'), ('AMATH', 'Applied Math'), ('CHEM', 'Chemistry'), ('PHYS', 'Physics'), ('MECH', 'Mechanical Engineering'), ('BIOE', 'Bioengineering'), ('CS', 'Computer Science'), ('STAT', 'Statistics'), ('HAAS', 'Business'), ('PH', 'Public Health'), ('MCB', 'MCB'), ('BIO', 'Biology'), ('UND', 'Undecided'), ('NONE', 'Other')], default='UND', max_length=4),
        ),
    ]
