# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-02 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170401_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founder',
            name='seeking',
        ),
        migrations.AddField(
            model_name='founder',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='founder',
            name='field',
            field=models.CharField(blank=True, choices=[('EDUC', 'Education'), ('TECH', 'Technology'), ('RE', 'Retail'), ('HEAL', 'Health Care'), ('ECOM', 'E-Commerce'), ('MARK', 'Marketplaces'), ('FIN', 'Finance'), ('HARD', 'Hardware'), ('MANG', 'Management/Consulting'), ('LEG', 'Legal'), ('MED', 'Medical'), ('HOUS', 'Real Estate'), ('AUTO', 'Automotive'), ('ENER', 'Energy'), ('MACH', 'Machinery'), ('ENV', 'Environmental'), ('NONE', 'Other')], max_length=4),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.CharField(choices=[('0', 'Partnership'), ('1', 'Paid')], default='1', max_length=1),
        ),
    ]
