# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-07 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_profile_default_values_fix'),
        ('website', '0004_myuser_is_individual'),
    ]

    operations = [
    ]
