# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-25 03:26
from __future__ import unicode_literals

from django.db import migrations
import website.profile


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20171010_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='logo',
            field=website.profile.CustomImageField(default=None, upload_to=website.profile.company_logo_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=website.profile.CustomImageField(default=None, upload_to=website.profile.user_directory_path),
        ),
    ]
