# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-07 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_merge_20170807_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.CharField(choices=[('0', 'Partnership'), ('1', 'Paid'), ('NONE', 'Other')], default='1', max_length=1, verbose_name='Pay'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('0', 'Partnership'), ('1', 'Paid'), ('NONE', 'Other')], default='NONE', max_length=4, verbose_name='Position'),
        ),
    ]
