# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-08 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170807_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_account_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
