# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-15 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import website.profile


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20171025_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='test_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='founder',
            name='logo',
            field=website.profile.CustomImageField(blank=True, null=True, upload_to=website.profile.company_logo_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=website.profile.user_directory_path),
        ),
    ]
