# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-07 07:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    profile = apps.get_model("website", "Profile")

    db_alias = schema_editor.connection.alias
    profile.objects.using(db_alias).filter(position='0').update(positions=[0])
    profile.objects.using(db_alias).filter(position='1').update(positions=[1])
    profile.objects.using(db_alias).filter(position='NONE').update(positions=[])


def reverse_func(apps, schema_editor):
    profile = apps.get_model("website", "Profile")

    db_alias = schema_editor.connection.alias
    profile.objects.using(db_alias).filter(positions=[0]).update(position='0')
    profile.objects.using(db_alias).filter(positions=[1]).update(position='1')


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_profile_default_values_fix'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE',
                          reverse_sql=migrations.RunSQL.noop),
        migrations.AddField(
            model_name='profile',
            name='positions',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(choices=[(0, 'Paid'), (1, 'Partnership'), (2, 'Contract')], default=0),
                default=[0], size=None),
        ),
        migrations.RunPython(forwards_func, reverse_func, atomic=True),
        migrations.RunSQL(migrations.RunSQL.noop,
                          reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
    ]
