# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-17 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20171115_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='feedback',
            field=models.BooleanField(default=False, verbose_name='Feedback'),
        ),
    ]
