# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-15 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import website.profile


def forwards_func(apps, schema_editor):
    myuser = apps.get_model("website", "myuser")

    db_alias = schema_editor.connection.alias
    myuser.objects.using(db_alias).filter(is_founder=False).update(is_individual=True)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_profile_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='alt_email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_account_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('IN', 'Intern'), ('CT', 'Contract')], default='FT', max_length=2, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.CharField(choices=[('0', 'Partnership'), ('1', 'Paid'), ('NONE', 'Other')], default='1', max_length=5, verbose_name='Pay'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alt_email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(choices=[('EECS', 'Electrical Engineering and Computer Science'), ('IEOR', 'Industrial Engineering and Operations Research'), ('ECON', 'Economics'), ('AMATH', 'Applied Math'), ('CHEM', 'Chemistry'), ('PHYS', 'Physics'), ('MECH', 'Mechanical Engineering'), ('BIOE', 'Bioengineering'), ('CS', 'Computer Science'), ('STAT', 'Statistics'), ('HAAS', 'Business'), ('PH', 'Public Health'), ('MCB', 'MCB'), ('BIO', 'Biology'), ('UND', 'Undecided'), ('NONE', 'Other')], default='UND', max_length=5, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='positions',
            field=website.profile.ChoiceArrayField(base_field=models.CharField(choices=[('0', 'Partnership'), ('1', 'Intern'), ('2', 'Part-Time'), ('3', 'Full-Time'), ('4', 'Contract')], default='0', max_length=1), default=['0'], size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate'), ('PH', 'PhD'), ('PD', 'Post-Doc'), ('AL', 'Alumni'), ('FC', 'Faculty'), ('NONE', 'Other')], default='NONE', max_length=4, verbose_name='Year'),
        ),
        migrations.RunPython(forwards_func, reverse_func, atomic=True),
    ]
