# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20170327_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Profile'),
        ),
    ]
