# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-20 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20171120_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_date',
        ),
    ]
