# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-22 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_job_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mentor',
            field=models.BooleanField(default=False, verbose_name='Willing to mentor'),
        ),
    ]
