# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170327_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hours_week',
            field=models.CharField(choices=[('0', '0 - 5'), ('1', '5 - 10'), ('2', '10 - 15'), ('3', '15 - 20'), ('4', '20+')], default='0', max_length=1),
        ),
    ]
