# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-24 07:36
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone
from django.db.models import F


def forwards_func(apps, schema_editor):
    user = apps.get_model("website", "MyUser")
    db_alias = schema_editor.connection.alias
    user.objects.using(db_alias).all().update(last_activity=F('last_login'))


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_profile_mentor'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE',
                          reverse_sql=migrations.RunSQL.noop),
        migrations.AddField(
            model_name='myuser',
            name='last_activity',
            field=models.DateTimeField(default=timezone.now(), null=True),
        ),
        migrations.RunPython(forwards_func, reverse_func, atomic=True),
        migrations.RunSQL(migrations.RunSQL.noop,
                          reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
    ]
