# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-24 07:36
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone
from django.db.models import F


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_profile_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_activity',
            field=models.DateTimeField(default=timezone.now(), null=True),
        ),
    ]
