# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import website.profile


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20170327_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='logo',
            field=models.ImageField(blank=True, default='images/default/default-logo.jpg', upload_to=website.profile.company_logo_path),
        ),
    ]
