# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20170327_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with this email address already exists'}, help_text='Must be a @berkeley.edu email', max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
