# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20170331_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40)),
                ('pay', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('level', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('IN', 'Intern')], default='FT', max_length=2)),
                ('founder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Founder')),
            ],
        ),
    ]
