# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-14 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20171211_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
